// Triage prompt (9.2 — Pre-execution complexity estimation)
// Model: Haiku (fast, cheap). Runs after codebase-index, before specify.
// Output: TRIAGE_RESULT JSON block parsed by index.ts.
// critical complexity → CriticalComplexityError unless --force-triage.

export function buildTriagePrompt(
  featureName: string,
  featureDescription: string,
  runHistory?: string,
  agentPerfLog?: string,
): string {
  const runContextSection = (runHistory || agentPerfLog)
    ? `\n<run_context>\n${runHistory ? `## Past runs in this project\n${runHistory}\n` : ""}${agentPerfLog ? `\n## Agent performance (cross-project)\n${agentPerfLog}\n` : ""}</run_context>\n`
    : "";

  return `You are a triage engine. Estimate the cost and risk of implementing a feature BEFORE the full pipeline runs. Be fast and decisive — one round of reading is enough.${runContextSection}
<feature>
${featureDescription}
</feature>

<instructions>
1. Read specs/${featureName}/codebase-map.md (generated by the previous stage).
2. Use run_context (if present) to calibrate estimates — past fix_loops indicate real-world complexity for this project.
3. Based on the feature description and codebase map, estimate:
   - complexity: "low" (1–3 tasks, isolated change), "medium" (4–8 tasks, a few modules), "high" (9–15 tasks, cross-cutting concern), "critical" (>15 tasks OR risky refactor of core/shared code)
   - estimated_tasks: integer — expected number of atomic implementation tasks
   - estimated_files: integer — expected number of files touched
   - regression_risk: "low" (no shared code touched), "medium" (shared utilities modified), "high" (core modules or public APIs changed)
   - estimated_tokens: rough total tokens for implement + verify + review combined
   - proceed: true unless complexity === "critical"
   - reason: one sentence explaining the assessment
3. Output the TRIAGE_RESULT block below.
</instructions>

<output_format>
Output this exact block after your analysis (no trailing whitespace inside the JSON):

TRIAGE_RESULT:
{
  "complexity": "low|medium|high|critical",
  "estimated_tasks": 0,
  "estimated_files": 0,
  "regression_risk": "low|medium|high",
  "estimated_tokens": 0,
  "proceed": true,
  "reason": "string"
}
</output_format>

Do NOT explain your process. Do NOT ask questions. Produce the TRIAGE_RESULT and stop.`;
}
